keypoints2d_map:
  head: 0
  neck:
    average: [5, 6]
  right_shoulder: 6
  right_elbow: 8
  right_wrist: 10
  left_shoulder: 5
  left_elbow: 7
  left_wrist: 9
  pelvis:
    average: [11, 12]
  right_hip: 12
  right_knee: 14
  right_ankle: 16
  left_hip: 11
  left_knee: 13
  left_ankle: 15
  left_toe: 17
  left_foot: 18
  right_toe: 20
  right_foot: 21
  left_hand: 101
  right_hand: 122
